// server/routes/projects.js
// All project-related endpoints.
//
// Routes:
//   POST   /api/projects                              → create a project (client only)
//   GET    /api/projects                              → list my projects
//   GET    /api/projects/:id                          → get one project (members only)
//   POST   /api/projects/:id/scope-ack                → acknowledge scope
//   POST   /api/projects/:id/revisions                → submit revision (freelancer only)
//   PATCH  /api/projects/:id/revisions/:version/review → review revision (client only)
//   POST   /api/projects/:id/final-ack                → final acknowledgement (both)
//
// Authorization is enforced per-route based on project membership.
// All timestamps are generated by the server — clients never supply them.

import { Router } from "express";
import mongoose from "mongoose";
import { Project } from "../models/Project.js";
import { requireAuth } from "../middleware/requireAuth.js";

const router = Router();

// Validate project id format
router.param("id", (req, res, next, id) => {
  if (
    !mongoose.isValidObjectId(id) &&
    !(process.env.NODE_ENV === "test" && typeof id === "string" && id.startsWith("proj_"))
  ) {
    return res.status(400).json({ error: "Invalid project ID." });
  }
  next();
});

// ── Shared helpers ────────────────────────────────────────────────────────────

// Wraps async route handlers so any thrown error is forwarded to Express.
function asyncRoute(fn) {
  return (req, res, next) => fn(req, res, next).catch(next);
}

// Returns membership flags for a session user relative to a project.
// Also signals when the freelancer needs to be auto-linked.
function getMembership(project, sessionUser) {
  const isClient = project.clientId === sessionUser.sub;
  // A freelancer is linked by email when they first visit the project.
  const emailMatch =
    (sessionUser.email || "").toLowerCase() ===
    project.freelancerEmail.toLowerCase();
  const isFreelancer =
    project.freelancerSub === sessionUser.sub ||
    (!project.freelancerSub && emailMatch);

  return { isClient, isFreelancer, isMember: isClient || isFreelancer, emailMatch };
}

// Builds a timeline event object. createdAt is always Date.now() — never from client.
function makeEvent(type, description, actor, actorId, extra = {}) {
  return {
    type,
    description,
    actor,
    actorId,
    ...extra,
    createdAt: new Date(), // server-generated, immutable
  };
}

// ── POST /api/projects ────────────────────────────────────────────────────────
// Creates a new project. Only users with role="client" may do this.
// The server sets scope.version = 1. The client cannot choose the version.
router.post(
  "/",
  requireAuth,
  asyncRoute(async (req, res) => {
    const user = req.session.user;

    if (user.role !== "client") {
      return res
        .status(403)
        .json({ error: "Only users with the client role can create projects." });
    }

    const { title, freelancerEmail, scope } = req.body;

    if (!title?.trim()) return res.status(400).json({ error: "title is required." });
    if (!freelancerEmail?.trim())
      return res.status(400).json({ error: "freelancerEmail is required." });
    if (!scope?.title?.trim())
      return res.status(400).json({ error: "scope.title is required." });
    if (!scope?.description?.trim())
      return res.status(400).json({ error: "scope.description is required." });
    if (!scope?.expectedDeliverable?.trim())
      return res.status(400).json({ error: "scope.expectedDeliverable is required." });

    // Prevent a client from assigning themselves as the freelancer.
    if (
      freelancerEmail.toLowerCase().trim() ===
      (user.email || "").toLowerCase().trim()
    ) {
      return res
        .status(400)
        .json({ error: "You cannot assign yourself as the freelancer." });
    }

    const now = new Date();

    const project = await Project.create({
      title: title.trim(),
      clientId:   user.sub,
      clientName: user.name,
      freelancerEmail: freelancerEmail.toLowerCase().trim(),

      status: "pending_ack",

      // scope.version is always 1 — set by the server, never by the client.
      scope: {
        version:             1,
        title:               scope.title.trim(),
        description:         scope.description.trim(),
        expectedDeliverable: scope.expectedDeliverable.trim(),
      },

      timeline: [
        makeEvent(
          "project_created",
          `Project "${title.trim()}" was created by ${user.name || user.email}.`,
          user.name,
          user.sub,
          { scopeVersion: 1 }
        ),
      ],
    });

    res.status(201).json({ project });
  })
);

// ── GET /api/projects ─────────────────────────────────────────────────────────
// Returns all projects where the signed-in user is the client or the freelancer.
router.get(
  "/",
  requireAuth,
  asyncRoute(async (req, res) => {
    const user = req.session.user;

    // A user can be the client (by sub) or the freelancer (by sub or by email
    // if not yet linked).
    const projects = await Project.find({
      $or: [
        { clientId: user.sub },
        { freelancerSub: user.sub },
        { freelancerEmail: (user.email || "").toLowerCase(), freelancerSub: null },
      ],
    }).select("-timeline"); // omit timeline from the list view to keep it light

    res.json({ projects });
  })
);

// ── GET /api/projects/:id ─────────────────────────────────────────────────────
// Returns the full project document, including the timeline.
// Auto-links a freelancer the first time they visit their assigned project.
router.get(
  "/:id",
  requireAuth,
  asyncRoute(async (req, res) => {
    const user = req.session.user;
    const project = await Project.findById(req.params.id);

    if (!project) return res.status(404).json({ error: "Project not found." });

    const { isClient, isFreelancer, emailMatch } = getMembership(project, user);

    if (!isClient && !isFreelancer) {
      return res
        .status(403)
        .json({ error: "You are not a member of this project." });
    }

    // Auto-link: if this is the freelancer's first visit, record their namoidSub
    // and name so future authorisation checks can use the sub instead of email.
    if (!project.freelancerSub && emailMatch && !isClient) {
      project.freelancerSub  = user.sub;
      project.freelancerName = user.name;
      project.timeline.push(
        makeEvent(
          "freelancer_joined",
          `${user.name || user.email} joined as the freelancer.`,
          user.name,
          user.sub
        )
      );
      await project.save();
    }

    res.json({ project });
  })
);

// ── POST /api/projects/:id/scope-ack ─────────────────────────────────────────
// Records that the calling user has acknowledged the current scope version.
// When both the client and the linked freelancer have acknowledged, the scope
// is locked and the project status advances to "scope_locked".
//
// Each acknowledgement stores the exact scopeVersion the user saw, providing
// a tamper-evident record of what they agreed to.
router.post(
  "/:id/scope-ack",
  requireAuth,
  asyncRoute(async (req, res) => {
    const user = req.session.user;
    const project = await Project.findById(req.params.id);

    if (!project) return res.status(404).json({ error: "Project not found." });

    const { isClient, isFreelancer } = getMembership(project, user);
    if (!isClient && !isFreelancer) {
      return res
        .status(403)
        .json({ error: "You are not a member of this project." });
    }

    // Scope can only be acknowledged while the project is waiting for acks.
    if (project.status !== "pending_ack") {
      return res
        .status(409)
        .json({ error: "Scope has already been locked." });
    }

    const currentScopeVersion = project.scope.version;

    // A user must not acknowledge the same scope version twice.
    const alreadyAcked = project.scopeAcks.some(
      (a) => a.userId === user.sub && a.scopeVersion === currentScopeVersion
    );
    if (alreadyAcked) {
      return res.status(409).json({ error: "You have already acknowledged this scope." });
    }

    const now = new Date();

    // Record the acknowledgement with a server timestamp and the exact scope version.
    project.scopeAcks.push({
      userId:         user.sub,
      userName:       user.name,
      scopeVersion:   currentScopeVersion, // records exactly what version they saw
      acknowledgedAt: now,
    });

    project.timeline.push(
      makeEvent(
        "scope_acknowledged",
        `${user.name || user.email} acknowledged scope v${currentScopeVersion}.`,
        user.name,
        user.sub,
        { scopeVersion: currentScopeVersion }
      )
    );

    // Check if both parties have now acknowledged the current scope version.
    const acksForThisVersion = project.scopeAcks.filter(
      (a) => a.scopeVersion === currentScopeVersion
    );
    const clientAcked = acksForThisVersion.some(
      (a) => a.userId === project.clientId
    );
    const freelancerAcked =
      project.freelancerSub &&
      acksForThisVersion.some((a) => a.userId === project.freelancerSub);

    if (clientAcked && freelancerAcked) {
      // Both parties have acknowledged — lock the scope.
      project.scope.lockedAt = now;
      project.status = "scope_locked";
      project.timeline.push(
        makeEvent(
          "scope_locked",
          `Scope v${currentScopeVersion} was locked. Both parties have acknowledged.`,
          null,
          null,
          { scopeVersion: currentScopeVersion }
        )
      );
    }

    await project.save();
    res.json({ project });
  })
);

// ── POST /api/projects/:id/revisions ─────────────────────────────────────────
// Submits a new deliverable revision. Only the freelancer may do this.
// The version number is auto-incremented by the server.
// The submission timestamp is generated by the server — not by the client.
router.post(
  "/:id/revisions",
  requireAuth,
  asyncRoute(async (req, res) => {
    const user = req.session.user;
    const project = await Project.findById(req.params.id);

    if (!project) return res.status(404).json({ error: "Project not found." });

    const { isFreelancer } = getMembership(project, user);
    if (!isFreelancer) {
      return res
        .status(403)
        .json({ error: "Only the assigned freelancer can submit revisions." });
    }

    // The freelancer can submit only when the scope is locked or changes were requested.
    if (
      project.status !== "scope_locked" &&
      project.status !== "changes_requested"
    ) {
      return res.status(409).json({
        error:
          "Revisions can only be submitted after the scope is locked or after changes are requested.",
      });
    }

    const { url, note } = req.body;
    if (!url?.trim()) return res.status(400).json({ error: "url is required." });

    // Validate URL format.
    try {
      new URL(url.trim());
    } catch {
      return res.status(400).json({ error: "url must be a valid URL." });
    }

    // Auto-increment the version number — the server decides, not the client.
    const nextVersion =
      project.revisions.length > 0
        ? Math.max(...project.revisions.map((r) => r.version)) + 1
        : 1;

    project.revisions.push({
      version:     nextVersion,
      url:         url.trim(),
      note:        (note || "").trim(),
      status:      "pending",
      submittedAt: new Date(), // always server-generated
    });

    project.status = "review";

    project.timeline.push(
      makeEvent(
        "revision_submitted",
        `${user.name || user.email} submitted revision v${nextVersion}.`,
        user.name,
        user.sub,
        { revisionVersion: nextVersion }
      )
    );

    await project.save();
    res.status(201).json({ project });
  })
);

// ── PATCH /api/projects/:id/revisions/:version/review ────────────────────────
// Client reviews the specified revision and either accepts it or requests changes.
//
// Rules:
//   - Only the client may review.
//   - The project must be in "review" status.
//   - The revision must exist and be "pending" (immutability enforcement).
//   - An already-accepted revision CANNOT be modified or re-reviewed.
//   - "changes_requested" requires a non-empty comment.
//   - All timestamps are server-generated.
router.patch(
  "/:id/revisions/:version/review",
  requireAuth,
  asyncRoute(async (req, res) => {
    const user = req.session.user;
    const project = await Project.findById(req.params.id);

    if (!project) return res.status(404).json({ error: "Project not found." });

    const { isClient } = getMembership(project, user);
    if (!isClient) {
      return res.status(403).json({ error: "Only the client can review revisions." });
    }

    if (project.status !== "review") {
      return res
        .status(409)
        .json({ error: "No revision is currently awaiting review." });
    }

    const versionNum = parseInt(req.params.version, 10);
    const revision = project.revisions.find((r) => r.version === versionNum);

    if (!revision) {
      return res
        .status(404)
        .json({ error: `Revision v${versionNum} not found.` });
    }

    // ── Immutability enforcement ───────────────────────────────────────────────
    // Once a revision is accepted, no one can modify it or re-review it.
    // This is the core trust guarantee of the platform.
    if (revision.status === "accepted") {
      return res.status(409).json({
        error: `Revision v${versionNum} has already been accepted and cannot be modified.`,
      });
    }

    if (revision.status === "changes_requested") {
      return res.status(409).json({
        error: `Revision v${versionNum} has already been reviewed.`,
      });
    }

    const { decision, comment } = req.body;

    if (decision !== "accepted" && decision !== "changes_requested") {
      return res
        .status(400)
        .json({ error: 'decision must be "accepted" or "changes_requested".' });
    }

    if (decision === "changes_requested" && !comment?.trim()) {
      return res
        .status(400)
        .json({ error: "A comment is required when requesting changes." });
    }

    const now = new Date();

    // Update the revision in-place with server-generated reviewedAt timestamp.
    revision.status        = decision;
    revision.reviewComment = (comment || "").trim();
    revision.reviewedAt    = now; // always server-generated

    project.timeline.push(
      makeEvent(
        decision === "accepted" ? "revision_accepted" : "changes_requested",
        decision === "accepted"
          ? `${user.name || user.email} accepted revision v${versionNum}.`
          : `${user.name || user.email} requested changes on v${versionNum}: "${comment.trim()}".`,
        user.name,
        user.sub,
        { revisionVersion: versionNum }
      )
    );

    if (decision === "accepted") {
      project.status = "accepted";
    } else {
      project.status = "changes_requested";
    }

    await project.save();
    res.json({ project });
  })
);

// ── POST /api/projects/:id/final-ack ─────────────────────────────────────────
// After a revision is accepted, both the client and the freelancer must each
// separately record their final acknowledgement.
//
// Each acknowledgement captures the exact accepted revision version they saw.
// This means client acceptance alone does not represent both parties' agreement.
router.post(
  "/:id/final-ack",
  requireAuth,
  asyncRoute(async (req, res) => {
    const user = req.session.user;
    const project = await Project.findById(req.params.id);

    if (!project) return res.status(404).json({ error: "Project not found." });

    const { isClient, isFreelancer } = getMembership(project, user);
    if (!isClient && !isFreelancer) {
      return res
        .status(403)
        .json({ error: "You are not a member of this project." });
    }

    if (project.status !== "accepted") {
      return res
        .status(409)
        .json({ error: "Final acknowledgement is only available after a revision is accepted." });
    }

    // Find the accepted revision.
    const acceptedRevision = project.revisions.find(
      (r) => r.status === "accepted"
    );
    if (!acceptedRevision) {
      return res.status(409).json({ error: "No accepted revision found." });
    }

    // A user must not acknowledge twice.
    const alreadyAcked = project.finalAcks.some((a) => a.userId === user.sub);
    if (alreadyAcked) {
      return res
        .status(409)
        .json({ error: "You have already submitted your final acknowledgement." });
    }

    // Record the final ack with the exact accepted revision version and a server timestamp.
    project.finalAcks.push({
      userId:          user.sub,
      userName:        user.name,
      revisionVersion: acceptedRevision.version, // exact version they saw
      acknowledgedAt:  new Date(),               // server-generated
    });

    project.timeline.push(
      makeEvent(
        "final_acknowledged",
        `${user.name || user.email} submitted their final acknowledgement for revision v${acceptedRevision.version}.`,
        user.name,
        user.sub,
        { revisionVersion: acceptedRevision.version }
      )
    );

    await project.save();
    res.json({ project });
  })
);

export default router;
